### ISSUE TITLE
detail | 상품 후기&문의 모달 기능

### ISSUE THREAD

**Issue by no-support** [LIKELION-REACT-16/Market-Karly#145]
## Feature Description

상품 후기&문의 모달 상세 기능 구현

## To-Do

- [x] 후기 및 문의하기 모달 닫기
- [x] textArea 클릭 시 placeholder div가 보이지 않게
- [x] textArea 포커스 아웃 시 placeholder div가 다시 보이게
- [x] 모달을 닫았다가 다시 열었을 때 작성중이었던 글의 내용이 사라지게
- [x] 글 작성
- [x] 글자 입력 수 카운트
- [x] 글자 수가 5000글자 이상일 시 잘라내기(->10글자로 변경)
- [x] 유효성 검사 통과 시 등록 버튼 스타일링 변경
- [x] 후기 등록

### 추가 사항

여기에 작성하세요
