### ISSUE TITLE
Cart | Firebase 데이터 연동 및 세션 데이터 비교

### ISSUE THREAD

**Issue by ukssss** [LIKELION-REACT-16/Market-Karly#165]
## Feature Description

Firebase 데이터 연동 작업

## To-Do

- [x] Firestore 데이터 불러오기
- [x] Firestore 데이터 화면 렌더링
- [x] 세션 데이터 가져오기
- [x] 세션 데이터 비교해서 조건에 맞는 값 장바구니 출력

### 추가 사항

X
