### ISSUE TITLE
Deploy | gh-pages 배포 작업

### ISSUE THREAD

**Issue by ukssss** [LIKELION-REACT-16/Market-Karly#196]
## Feature Description

gh-pages 배포 작업

## To-Do

- [x] vite.config.js 수정
- [x] package.json 수정
- [x] gh-pages 배포

### 추가 사항

x
